# Generated by Django 3.1.4 on 2020-12-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('referencia', models.CharField(max_length=5)),
                ('preco', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'Produto',
            },
        ),
    ]
