# Generated by Django 3.1.4 on 2020-12-14 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('referencia', models.CharField(max_length=5)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagem', models.ImageField(null=True, upload_to='images')),
                ('quantidade', models.IntegerField(null=True)),
                ('promocao', models.BooleanField(default=False, null=True)),
                ('precopromocao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('categoria', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Produto',
            },
        ),
    ]
