# Generated by Django 3.1.4 on 2020-12-13 15:46

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_produto_imagem'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='produto',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(null=True),
        ),
    ]
