# Generated by Django 3.1.4 on 2020-12-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_auto_20201213_1246'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='produto',
            managers=[
            ],
        ),
    ]
