# Generated by Django 3.1.4 on 2020-12-13 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_auto_20201213_1310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
