# Generated by Django 3.1.4 on 2020-12-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0007_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='precopromocao',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='promocao',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.CharField(max_length=15),
        ),
    ]
